### ISSUE TITLE
Haskell package regex-pcre: update it or find alternative

### ISSUE THREAD

**Issue by thielema** [ganeti/ganeti#1744]
The package libghc-regex-pcre-dev is gone in Debian Trixie. [1]
It depends on the C library libpcre3, which is abondened. [2]
A possible successor to this library is PCRE2.
The question is, whether to switch to a different Haskell regex library or update regex-pcre to PCRE2.
There has been work done for the second path, but there seems to be a blocking memory corruption bug. [3,4]

[1] https://tracker.debian.org/news/1495182/haskell-regex-pcre-removed-from-testing/
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000067
[3] https://github.com/haskell-hvr/regex-pcre/issues/1
[4] https://github.com/sjshuck/hs-pcre2/issues/34

**Comment by rbott** [comment]
How about the alternatives listed here:

https://wiki.haskell.org/Regular_expressions

I am not very involved with Haskell so this might me nonsense :-)

**Comment by saschalucas** [comment]
More context can be found here https://github.com/ganeti/ganeti/blob/ceff246e30547d6a10eef27a2d91edce24f05d3e/NEWS?plain=1#L1223-L1224
Seems like a feature I didn't know before: https://github.com/ganeti/ganeti/blob/ceff246e30547d6a10eef27a2d91edce24f05d3e/man/gnt-filter.rst Does anybody use this?

Maybe a third option would be, to remove this feature?

**Comment by rbott** [comment]
The man page sounds a bit like it's required for cluster operation, but maybe that's just ambiguous wording:

> Filter rules are used by the Ganeti job scheduler to determine which jobs should be accepted, rejected, paused or rate-limited.

The rest of the man page sounds more like it's an optional feature which helps with cluster (more specific: job maintenance).

I'll look into this a bit more later.

**Comment by thielema** [comment]
On Tue, 2 Jul 2024, Rudolph Bott wrote:

> How about the alternatives listed here:
> 
> https://wiki.haskell.org/Regular_expressions

Looks like a good overview. I think we must answer the question, whether 
we want Perl or POSIX regular expressions. It seems that POSIX has better 
support for Haskell-only implementations. A Haskell-only implementation is 
less prone to memory corruption bugs or interfacing issues to external 
libraries. I do not know how many people rely on Perl regexes in existing 
installations, though.

It seems the last substantial update to that Wiki page was in 2014. There 
may be newer regex libraries. I do not use regexes myself in Haskell, 
because it is easier and more flexible and more comprehensible to write 
'parsec' parsers in Haskell. More research might reveal newer and better 
alternatives.

**Comment by saschalucas** [comment]
@thielema: don't know what's on your priority list. From my perspective regarding "works in current debian testing" this seems rather high?

I don't know how much Ganeti depends internally on Perl compatible regexs. I could image, that POSIX would be sufficient???

**Comment by thielema** [comment]
On Tue, 30 Jul 2024, saschalucas wrote:

> @thielema: don't know what's on your priority list. From my perspective 
> regarding "works in current debian testing" this seems rather high?

I also consider the regex-pcre issue as high priority, but it competes 
with the Cabal-build effort.

> I don't know how much Ganeti depends internally on Perl compatible 
> regexs. I could image, that POSIX would be sufficient???

I am afraid that POSIX and Perl expressions are sufficiently different and 
changing them would cause silent breakage for the people out in the world 
who use it. So currently I would try to go with pcre2. My questions about 
regex library recommendations seemed to cause some activities on the 
Haskell interface to pcre2.

**Comment by saschalucas** [comment]
> ... So currently I would try to go with pcre2. My questions about regex library recommendations seemed to cause some activities on the Haskell interface to pcre2.

Is there something present in Debian for using Haskell and pcre2? I'm unable to find a corresponding libghc package. Or do we hope that libghc-regex-pcre-dev is switching to pcre2? And then later reintroduce it as a Debian package?

If there is no Debian package available, the obvious solution would be to switch to an other regex provider. I would even consider breaking Perl regex.

**Comment by thielema** [comment]
Currently I would first try https://hackage.haskell.org/package/pcre2 .
I am afraid switching the regular expression language will cause unexpected breakage for users.
If it fits our needs, then I would propose it as Debian package.
If it is not accepted for Debian or not fast enough for Trixie, then I would build pcre2 as part of the Ganeti Debian build process. We would also need this for supporting older Debian and Ubuntu versions. Other distributions might already provide `hs-pcre2`.

**Comment by thielema** [comment]
In `Ganeti.Query.Language` there are some CPP switches on the flag `VERSION_regex_pcre` that look like they would allow to compile the modules when no `regex-pcre` bindings are available. This was introduced with ed0fec42533966b7a42160d1cd55a95a4dc9ed27. At this time, package dependency on `regex-pcre` was guarded by the Cabal flag `confd` in `cabal/ganeti.cabal.template`. This has gone since then.

Today, removing the dependency on `regex-pcre` does not work anymore, because in case of missing `regex-pcre` the type for compiled regexes is set to `()` (this is the unit type, or nullary tuple) and this is no valid type for compiled regexes. It causes the type error:
~~~~
src/Ganeti/Query/Filter.hs:174:9: error:
    • No instance for (RegEx.RegexLike () [Char])
        arising from a use of ‘RegEx.match’
~~~~

Thus I think I will remove this conditional compilation to simplify matters.

**Comment by thielema** [comment]
Btw. disabling RegEx matches would be a way to detect the worldwide users of this feature. :-)

**Comment by thielema** [comment]
Here is a preview on how a switch to `regex-tdfa` might look like:
https://github.com/thielema/ganeti/tree/regex-tdfa
CI fails with missing GHC package `regex-tdfa`, although I adapted `build_chroot` and `configure.ac`, accordingly.

Anyway, I think I should make `regex-tdfa` only a compile-time option.
Currently I think that chances are good that `regex-pcre` can be moved to `pcre2` by just raising the upper bound of the C library from 8 to 10, or so.

**Comment by saschalucas** [comment]
> Here is a preview on how a switch to `regex-tdfa` might look like: https://github.com/thielema/ganeti/tree/regex-tdfa

That looks like my favorite solution, because of an available Debian package, even if I have no glue if missing PCRE would break something/somebody's cluster. @rbott? @apoikos?

> CI fails with missing GHC package `regex-tdfa`, although I adapted `build_chroot` and `configure.ac`, accordingly.

`build_chroot` seems unused for a decade or so. Today containers have superseded chroots. Please make a PR against https://github.com/ganeti/ci-images and add `libghc-regex-tdfa-dev` in the `ganeti/Dockerfile.*`.

**Comment by thielema** [comment]
On Fri, 9 Aug 2024, saschalucas wrote:

>       Here is a preview on how a switch to regex-tdfa might look like:
>       https://github.com/thielema/ganeti/tree/regex-tdfa
> 
> That looks like my favorite solution, because of an available Debian package, even if I have no glue if missing PCRE would
> break something/somebody's cluster. @rbott? @apoikos?

Please wait with accepting. I want to put together an alternative 
proposal. I want to make regex-tdfa an Cabal option. Then regex-pcre can 
be used as long as it is available in Debian and the Debian maintainer can 
switch to regex-tdfa when it becomes necessary.

**Comment by saschalucas** [comment]
> Please wait with accepting. I want to put together an alternative proposal. I want to make regex-tdfa an Cabal option. Then regex-pcre can be used as long as it is available in Debian and the Debian maintainer can switch to regex-tdfa when it becomes necessary.

Yes, I'll wait for a PR. For now only #1784 has been accepted, but not yet merged.

**Comment by thielema** [comment]
At closer inspection, https://github.com/sjshuck/hs-pcre2/ is not so easy as upgrade path. It does not only not implement `regex-base` type classes (as `regex-pcre` and `regex-tdfa` do), but it also does not depend on `libpcre2`, instead it maintains a local copy of the `libpcre2` C source code. I do not know how they intend to stay up-to-date with fixes in `libpcre2`. Maybe the bug they encountered is something that is already fixed in upstream `libpcre2`. So, if we want to use `hs-pcre2` we would right away need a fork (good name would be `regex-pcre2`, that both instantiates `regex-base` type classes and binds to `libpcre2` library. I think, that's doable, though more effort than switching to `regex-tdfa`, of course.

**Comment by thielema** [comment]
There is also https://hackage.haskell.org/package/regex-pcre-builtin
They also copied library C code of libpcre to the Haskell package. This is good since this will still work, if old `libpcre` is dropped from Debian. But this is also bad, since they have to maintain and fix the C code themselves.
It would be a drop-in replacement, since it implements `regex-base` type classes.

**Comment by thielema** [comment]
Another player in the game:
https://github.com/robwithhair/hpcre2/blob/master/hpcre2.cabal
However, not yet published on Hackage (and thus not in Debian) and without `regex-base` instances.

**Comment by saschalucas** [comment]
I'm closing this, because with #1794 there is an alternative within Debian available (tdfa). We will see whether POSIX is sufficient or if we really need PCRE.

**Comment by thielema** [comment]
There is now also:
https://hackage.haskell.org/package/regex-pcre2

So in principle we could re-add pcre2 as an option.
