### ISSUE TITLE
GHC show an error after compiles Exec.hs file.

### ISSUE THREAD

**Issue by rchatsiri** [ganeti/ganeti#1452]
I'm build source code from master branch. GHC compiler shows an error as below.
```
[GHC]: src/Ganeti/Query/Exec.o <- cabal_macros.h src/Ganeti/Query/Exec.hs src/Ganeti/UDSServer.hi src/Ganeti/UDSServer.o src/Ganeti/Types.hi src/Ganeti/Types.o src/Ganeti/Path.hi src/Ganeti/Path.o src/Ganeti/OpCodes.hi src/Ganeti/OpCodes.o src/Ganeti/Logging/WriterLog.hi src/Ganeti/Logging/WriterLog.o src/Ganeti/Logging.hi src/Ganeti/Logging.o src/Ganeti/JSON.hi src/Ganeti/JSON.o src/Ganeti/JQueue/Objects.hi src/Ganeti/JQueue/Objects.o src/Ganeti/BasicTypes.hi src/Ganeti/BasicTypes.o src/AutoConf.hi src/AutoConf.o

src/Ganeti/Query/Exec.hs:120:12: error:
    Variable not in scope:
      getPid :: ProcessHandle -> IO (Maybe ProcessID)
```
Additional information
* The Glorious Glasgow Haskell Compilation System, version 8.0.2.
* cabal-install version 1.24.0.2.

**Comment by saschalucas** [comment]
According to the named versions, I assume this is an Ubuntu 18.04/Bionic build? If not please specify your Distribution and/or the source of your GHC environment (i.e. Stack or Haskell Platform). You may also attach the output of `cabal list --simple-output`

**Comment by saschalucas** [comment]
in Ubuntu 18.04 the Haskell package `process` is version 1.4.3.0, but in commit 219b2ab926c8d2ec6157c6e87636d1b7ba031789 getPid was introduced in https://github.com/ganeti/ganeti/blob/fc0b28b91a92a58850676dd077aa9f89d7a81958/src/Ganeti/Query/Exec.hs#L119, which is only available since [process-1.6.3.0](https://hackage.haskell.org/package/process-1.6.3.0/changelog).

Therefore we need to update the Haskell requirements https://github.com/ganeti/ganeti/blob/fc0b28b91a92a58850676dd077aa9f89d7a81958/cabal/ganeti.template.cabal#L55.

ATM this would mean, that a build on stock Ubuntu-18.04 packages is not possible.

**Comment by saschalucas** [comment]
I'm attaching a quick and dirty [patch for Ubuntu 18](https://github.com/ganeti/ganeti/files/4630929/ubu18.patch.gz). With that patch it compiles for me (also passes py-tests and hs-tests).

**Comment by rchatsiri** [comment]
After patch  a file involved an error finished. Source code was built completed without an error. Many thank. @saschalucas
